INSERT INTO CREATED (ID, TXT) VALUES 
(1, 'ABNW'),
(2, 'ABNW, NQNT'),
(3, 'Aleksandr Zapragajev'),
(4, 'Ales Bican, ABNW'),
(5, 'Ales Bican, PPQ'),
(6, 'Alex Grigny de Castro, PPQ'),
(7, 'Alexander Zapragajev'),
(8, 'Ambar Eldaron'),
(9, 'Boris Shapiro'),
(10, 'Boris Shapiro, Helge Fauskanger, PPQ'),
(11, 'Boris Shapiro, PPQ'),
(12, 'Boris Shapiro, PPQ, NQNT'),
(13, 'Boris Shapiro, Petri Tikka, PPQ'),
(14, 'Common'),
(15, 'Damien Bador'),
(16, 'David Kiltz, PPQ'),
(17, 'David Kiltz, PPQ, Helge Fauskanger, NQNT'),
(18, 'David Salo'),
(19, 'David Salo, Fiona Jallings, FJNS'),
(20, 'David Salo, GS'),
(21, 'David Salo, GS, Ambar Eldaron'),
(22, 'David Salo, PPQ'),
(23, 'David Salo, VQP'),
(24, 'Didier Willis'),
(25, 'Didier Willis, PPQ'),
(26, 'Dírheron'),
(27, 'Eddin Najetovic, PPQ'),
(28, 'Elaran'),
(29, 'Elaran, Fiona Jallings, FJNS'),
(30, 'Elaran, Hialmr'),
(31, 'Elaran, Hialmr, VQP'),
(32, 'Eli Bar-Yahalom, PPQ'),
(33, 'Elvishmouse'),
(34, 'EruannoVG'),
(35, 'Fayanzār'),
(36, 'Fiona Jallings'),
(37, 'Fiona Jallings, Elaran'),
(38, 'Fiona Jallings, FGNS'),
(39, 'Fiona Jallings, FJNS'),
(40, 'Fiona Jallings, NGNS'),
(41, 'Greta Rudolph, Boris Shapiro, PPQ'),
(42, 'Greta Rudolph, PPQ'),
(43, 'Gábor Lőrinczi'),
(44, 'Gábor Lőrinczi, VQP'),
(45, 'HSD, Paul Strack'),
(46, 'Helge Fauskanger'),
(47, 'Helge Fauskanger, NQNT'),
(48, 'Helge Fauskanger, NQNT, Aldaleon'),
(49, 'Helge Fauskanger, NQNT, NQ-Wiki'),
(50, 'Helge Fauskanger, NQNT, Robert Reynolds'),
(51, 'Helge Fauskanger, NQNT, Sami Paldanius'),
(52, 'Helge Fauskanger, NQNT, Tamas Ferencz'),
(53, 'Helge Fauskanger, PPQ'),
(54, 'Helge Fauskanger, VQP'),
(55, 'Hialmr'),
(56, 'Hialmr, Elaran'),
(57, 'Hialmr, VQP'),
(58, 'Hjalmar Holm'),
(59, 'Jack Harrison'),
(60, 'Jenna Carpenter'),
(61, 'Kevin B Walsh, VQP'),
(62, 'Lokyt'),
(63, 'Lucas Novak, PPQ'),
(64, 'Mans Bjorkman, PPQ'),
(65, 'Matt Dinse'),
(66, 'Matt Dinse, Hjalmar Holm'),
(67, 'Matt Dinse, VQP'),
(68, 'Mellonath Daeron, PPQ'),
(69, 'NQ-Wiki'),
(70, 'NQ-Wiki, NQNT'),
(71, 'NQ-Wiki, Tamas Ferencz'),
(72, 'Nicholas D. Kontovas, PPQ'),
(73, 'Orondil'),
(74, 'PPQ'),
(75, 'PPQ, Petri Tikka'),
(76, 'Paul Strack'),
(77, 'Paul Strack, Ambar Eldaron'),
(78, 'Paul Strack, Shihali'),
(79, 'Paul Strack, Ygrain'),
(80, 'Petri Tikka'),
(81, 'Petri Tikka, A.B., PPQ'),
(82, 'Petri Tikka, Eddin Najetovic, PPQ'),
(83, 'Petri Tikka, PPQ'),
(84, 'Raccoon'),
(85, 'Robert B Wilson, PPQ'),
(86, 'Robert Reynolds'),
(87, 'Robert Reynolds, Tamas Ferencz, Helge Fauskanger, PPQ'),
(88, 'Roman Rausch'),
(89, 'Roman Rausch, VQP'),
(90, 'Ryszard Derdzinski, PPQ'),
(91, 'Ryszard Derdzinski, PPW'),
(92, 'Röandil'),
(93, 'Sami Paldanius'),
(94, 'Sami Paldanius, VQP'),
(95, 'Sami Paldanius, VQP, Tamas Ferencz'),
(96, 'Shihali'),
(97, 'Shihali, Lokyt, Elaran, Paul Strack'),
(98, 'Stephen St. John'),
(99, 'Steve - Ríon'),
(100, 'Súlien'),
(101, 'Tamas Ferencz'),
(102, 'Tamas Ferencz, Alexander Zapragajev, VQP'),
(103, 'Tamas Ferencz, Helge Fauskanger, VQP'),
(104, 'Tamas Ferencz, PPQ'),
(105, 'Tamas Ferencz, Robert Reynolds'),
(106, 'Tamas Ferencz, Sami Paldanius'),
(107, 'Tamas Ferencz, VQP'),
(108, 'Terry Dock, PPQ'),
(109, 'Terry Dock, PPQ, Yitzik'),
(110, 'Thorsten Renk'),
(111, 'Unknown'),
(112, 'VQP'),
(113, 'Valeria Barouch, VQP'),
(114, 'Verilme'),
(115, 'Yitzik'),
(116, 'Yitzik, Tamas Ferencz'),
(117, 'Yitzik, VQP'),
(118, 'Ánweg'),
(119, 'Ицхак Пензев (Yitzik Penzev)');
