INSERT INTO CREATED (ID, TXT) VALUES 
(1, 'A.B.'),
(2, 'ABNW'),
(3, 'Aldaleon'),
(4, 'Aleksandr Zapragajev'),
(5, 'Ales Bican'),
(6, 'Alex Grigny de Castro'),
(7, 'Alexander Zapragajev'),
(8, 'Ambar Eldaron'),
(9, 'Boris Shapiro'),
(10, 'Common'),
(11, 'Damien Bador'),
(12, 'David Kiltz'),
(13, 'David Salo'),
(14, 'Didier Willis'),
(15, 'Dírheron'),
(16, 'Eddin Najetovic'),
(17, 'Elaran'),
(18, 'Eli Bar-Yahalom'),
(19, 'Elvishmouse'),
(20, 'EruannoVG'),
(21, 'FGNS'),
(22, 'FJNS'),
(23, 'Fayanzār'),
(24, 'Fiona Jallings'),
(25, 'GS'),
(26, 'Greta Rudolph'),
(27, 'Gábor Lőrinczi'),
(28, 'HSD'),
(29, 'Helge Fauskanger'),
(30, 'Hialmr'),
(31, 'Hjalmar Holm'),
(32, 'Jack Harrison'),
(33, 'Jenna Carpenter'),
(34, 'Kevin B Walsh'),
(35, 'Lokyt'),
(36, 'Lucas Novak'),
(37, 'Mans Bjorkman'),
(38, 'Matt Dinse'),
(39, 'Mellonath Daeron'),
(40, 'NGNS'),
(41, 'NQ-Wiki'),
(42, 'NQNT'),
(43, 'Nicholas D. Kontovas'),
(44, 'Orondil'),
(45, 'PPQ'),
(46, 'PPW'),
(47, 'Paul Strack'),
(48, 'Petri Tikka'),
(49, 'Raccoon'),
(50, 'Robert B Wilson'),
(51, 'Robert Reynolds'),
(52, 'Roman Rausch'),
(53, 'Ryszard Derdzinski'),
(54, 'Röandil'),
(55, 'Sami Paldanius'),
(56, 'Shihali'),
(57, 'Stephen St. John'),
(58, 'Steve - Ríon'),
(59, 'Súlien'),
(60, 'Tamas Ferencz'),
(61, 'Terry Dock'),
(62, 'Thorsten Renk'),
(63, 'Unknown'),
(64, 'VQP'),
(65, 'Valeria Barouch'),
(66, 'Verilme'),
(67, 'Ygrain'),
(68, 'Yitzik'),
(69, 'Ánweg'),
(70, 'Ицхак Пензев (Yitzik Penzev)');
